# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\..\Users\lenovo\workspace\TempMonitor\gui\MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 649)
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Box_data = QtGui.QGroupBox(self.centralwidget)
        self.Box_data.setGeometry(QtCore.QRect(40, 170, 731, 421))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Box_data.setFont(font)
        self.Box_data.setObjectName(_fromUtf8("Box_data"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Box_data)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableView_data = QtGui.QTableView(self.Box_data)
        self.tableView_data.setObjectName(_fromUtf8("tableView_data"))
        self.tableView_data.horizontalHeader().setHighlightSections(False)
        self.verticalLayout.addWidget(self.tableView_data)
        self.tableView_avg = QtGui.QTableView(self.Box_data)
        self.tableView_avg.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_avg.sizePolicy().hasHeightForWidth())
        self.tableView_avg.setSizePolicy(sizePolicy)
        self.tableView_avg.setMaximumSize(QtCore.QSize(16777215, 75))
        self.tableView_avg.setObjectName(_fromUtf8("tableView_avg"))
        self.verticalLayout.addWidget(self.tableView_avg)
        self.splitter_3 = QtGui.QSplitter(self.Box_data)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.btn_export_data = QtGui.QPushButton(self.splitter_3)
        self.btn_export_data.setObjectName(_fromUtf8("btn_export_data"))
        self.btn_sensor_stats = QtGui.QPushButton(self.splitter_3)
        self.btn_sensor_stats.setObjectName(_fromUtf8("btn_sensor_stats"))
        self.verticalLayout.addWidget(self.splitter_3)
        self.Box_connect_btns = QtGui.QGroupBox(self.centralwidget)
        self.Box_connect_btns.setGeometry(QtCore.QRect(20, 20, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Box_connect_btns.setFont(font)
        self.Box_connect_btns.setObjectName(_fromUtf8("Box_connect_btns"))
        self.btn_wifi = QtGui.QRadioButton(self.Box_connect_btns)
        self.btn_wifi.setGeometry(QtCore.QRect(120, 10, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_wifi.setFont(font)
        self.btn_wifi.setObjectName(_fromUtf8("btn_wifi"))
        self.btn_serial = QtGui.QRadioButton(self.Box_connect_btns)
        self.btn_serial.setGeometry(QtCore.QRect(260, 10, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_serial.setFont(font)
        self.btn_serial.setObjectName(_fromUtf8("btn_serial"))
        self.splitter_4 = QtGui.QSplitter(self.centralwidget)
        self.splitter_4.setGeometry(QtCore.QRect(510, 30, 251, 111))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.btn_Start = QtGui.QPushButton(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Start.setFont(font)
        self.btn_Start.setAutoFillBackground(False)
        self.btn_Start.setAutoDefault(False)
        self.btn_Start.setDefault(False)
        self.btn_Start.setFlat(False)
        self.btn_Start.setObjectName(_fromUtf8("btn_Start"))
        self.btn_Stop = QtGui.QPushButton(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Stop.setFont(font)
        self.btn_Stop.setAutoFillBackground(False)
        self.btn_Stop.setStyleSheet(_fromUtf8(""))
        self.btn_Stop.setObjectName(_fromUtf8("btn_Stop"))
        self.splitter_9 = QtGui.QSplitter(self.centralwidget)
        self.splitter_9.setGeometry(QtCore.QRect(50, 60, 421, 81))
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName(_fromUtf8("splitter_9"))
        self.box_wifi_settings = QtGui.QGroupBox(self.splitter_9)
        self.box_wifi_settings.setEnabled(True)
        self.box_wifi_settings.setTitle(_fromUtf8(""))
        self.box_wifi_settings.setCheckable(False)
        self.box_wifi_settings.setObjectName(_fromUtf8("box_wifi_settings"))
        self.splitter_5 = QtGui.QSplitter(self.box_wifi_settings)
        self.splitter_5.setGeometry(QtCore.QRect(10, 10, 171, 51))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.splitter = QtGui.QSplitter(self.splitter_5)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label_wifi_IP = QtGui.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_wifi_IP.setFont(font)
        self.label_wifi_IP.setObjectName(_fromUtf8("label_wifi_IP"))
        self.lineEdit_wifi_IP = QtGui.QLineEdit(self.splitter)
        self.lineEdit_wifi_IP.setObjectName(_fromUtf8("lineEdit_wifi_IP"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_5)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.label_wifi_port = QtGui.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_wifi_port.setFont(font)
        self.label_wifi_port.setObjectName(_fromUtf8("label_wifi_port"))
        self.lineEdit_wifi_port = QtGui.QLineEdit(self.splitter_2)
        self.lineEdit_wifi_port.setObjectName(_fromUtf8("lineEdit_wifi_port"))
        self.box_serial_settings = QtGui.QGroupBox(self.splitter_9)
        self.box_serial_settings.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.box_serial_settings.setFont(font)
        self.box_serial_settings.setTitle(_fromUtf8(""))
        self.box_serial_settings.setCheckable(False)
        self.box_serial_settings.setObjectName(_fromUtf8("box_serial_settings"))
        self.splitter_8 = QtGui.QSplitter(self.box_serial_settings)
        self.splitter_8.setGeometry(QtCore.QRect(10, 10, 181, 51))
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName(_fromUtf8("splitter_8"))
        self.splitter_6 = QtGui.QSplitter(self.splitter_8)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.label_serial_port = QtGui.QLabel(self.splitter_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_serial_port.setFont(font)
        self.label_serial_port.setObjectName(_fromUtf8("label_serial_port"))
        self.lineEdit_serial_port = QtGui.QLineEdit(self.splitter_6)
        self.lineEdit_serial_port.setObjectName(_fromUtf8("lineEdit_serial_port"))
        self.splitter_7 = QtGui.QSplitter(self.splitter_8)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.label_serial_baudrate = QtGui.QLabel(self.splitter_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_serial_baudrate.setFont(font)
        self.label_serial_baudrate.setObjectName(_fromUtf8("label_serial_baudrate"))
        self.combo_serial_baudrate = QtGui.QComboBox(self.splitter_7)
        self.combo_serial_baudrate.setObjectName(_fromUtf8("combo_serial_baudrate"))
        self.combo_serial_baudrate.addItem(_fromUtf8(""))
        self.combo_serial_baudrate.addItem(_fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.Box_data.setTitle(_translate("MainWindow", "Temperature Monitor:", None))
        self.btn_export_data.setText(_translate("MainWindow", "Export to Excel", None))
        self.btn_sensor_stats.setText(_translate("MainWindow", "Sensors Statistics", None))
        self.Box_connect_btns.setTitle(_translate("MainWindow", "Connect via:", None))
        self.btn_wifi.setText(_translate("MainWindow", "Wifi", None))
        self.btn_serial.setText(_translate("MainWindow", "Serial", None))
        self.btn_Start.setText(_translate("MainWindow", "Start", None))
        self.btn_Stop.setText(_translate("MainWindow", "Stop", None))
        self.label_wifi_IP.setText(_translate("MainWindow", "IP", None))
        self.label_wifi_port.setText(_translate("MainWindow", "PORT", None))
        self.label_serial_port.setText(_translate("MainWindow", "Serial Port", None))
        self.label_serial_baudrate.setText(_translate("MainWindow", "Baud-Rate", None))
        self.combo_serial_baudrate.setItemText(0, _translate("MainWindow", "9600", None))
        self.combo_serial_baudrate.setItemText(1, _translate("MainWindow", "115200", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

